#!/bin/sh

# Run from this directory
cd ${0%/*} || exit 1

export PYTHONPATH=${PWD}/../../../../src/structure/FEniCSx/src:$PYTHONPATH
export PYTHONPATH=${PWD}/../../../../coupling_lib/MUI/wrappers/Python:$PYTHONPATH

domainFluid=${PWD}/runData/fluidDomain
domainStructure=${PWD}/runData/structureDomain

# Ranks set to each domain
numProcsFluid=3
numProcsStructure=1

# Source OpenFOAM run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create and copy data to run folder
./runCtrl/runDataFolderCreation

# Get application name for structure domain
solverStructure=structureDomainRun.py

# Get application name for fluid domain
cd runData/fluidDomain
solverFluid=$(getApplication)
echo application is ${solverFluid}
cd ../../

# Pre-processing
./runCtrl/preProcess

echo -n "ParaSiF running..."

# ParaSiF case with OpenFOAM_MUI(C++)_MUI(python)_FEniCSx parallel run
mpirun -np ${numProcsFluid} -wdir ${domainFluid} ${solverFluid} -mpi-split-by-appnum -parallel :\
       -np ${numProcsStructure} -wdir ${domainStructure} python3 -m mpi4py ${solverStructure}\
        2>&1 | tee runData/logFiles/log.ParaSiFRun

echo "Done"

# Post-processing
./runCtrl/postProcess

# ----------------------------------------------------------------- end-of-file